#nullable enable
using Prometheus;
using Denis.TradingEngine.Core.Trading;

namespace Denis.TradingEngine.MetricsServer;

/// <summary>
/// Strategy metrike:
/// - koliko setup-ova nađeno
/// - koliko signala stvarno emitovano (BUY/SELL)
/// - koliko je blokirano (liquidity, activity, trend, atr, throttle...)
/// - atrFrac i trajanje pullbacka za debug / tuning
/// </summary>
public sealed class StrategyMetrics
{
    private static StrategyMetrics? _instance;
    private static readonly object Lock = new();

    private readonly Counter _setupsFoundTotal;
    private readonly Counter _signalsEmittedTotal;
    private readonly Counter _signalsBlockedTotal;
    private readonly Counter _signalsThrottledTotal;
        private readonly Counter _signalSlayerRejectedTotal;
        
        // Pullback state machine statistics (offline evaluacija)
        private readonly Counter _pullbackDetectedTotal;
        private readonly Counter _pullbackAbortedTotal;
        private readonly Counter _pullbackValidBreakoutTotal;

        // Time-of-day profiling: per-phase metrics
        private readonly Counter _signalsGeneratedByPhaseTotal;
        private readonly Counter _signalsAcceptedByPhaseTotal;
        private readonly Counter _signalsBlockedByPhaseTotal;
        private readonly Counter _signalSlayerRejectedByPhaseTotal;

        // Hold-time model: time-exit outcome logging
        private readonly Counter _timeExitOccurredTotal;
        private readonly Histogram _timeExitPnlDistribution; // P&L % distribucija posle time-exit-a

        // Trailing stop statistics
        private readonly Counter _trailingArmedTotal;
        private readonly Counter _trailingUpdateTotal;
        private readonly Counter _trailingFireTotal;
        private readonly Histogram _trailingPnlDistribution; // P&L % distribucija posle trailing exit-a

        // Multi-day swing: gap protection statistics
        private readonly Counter _gapExitExecutedTotal;
        private readonly Counter _gapDetectedOnOpenTotal;
        private readonly Histogram _gapExitPnlDistribution; // P&L % distribucija posle gap exit-a

    private readonly Gauge _atrFraction;
    private readonly Gauge _pullbackDurationSeconds;

    private StrategyMetrics()
    {
        // npr. PullbackInUptrendStrategy
        _setupsFoundTotal = Metrics.CreateCounter(
            "strategy_setups_found_total",
            "Number of valid setups found by strategy",
            new[] { "strategy", "symbol" }
        );

        _signalsEmittedTotal = Metrics.CreateCounter(
            "strategy_signals_emitted_total",
            "Number of trade signals emitted by strategy",
            new[] { "strategy", "symbol", "side" } // side: BUY/SELL
        );

        // reason: liquidity, activity, trend, atr, stale_quote, etc.
        _signalsBlockedTotal = Metrics.CreateCounter(
            "strategy_signals_blocked_total",
            "Number of potential signals blocked by filters",
            new[] { "strategy", "symbol", "reason" }
        );

        _signalsThrottledTotal = Metrics.CreateCounter(
            "strategy_signals_throttled_total",
            "Number of setups blocked by MinTimeBetweenSignals",
            new[] { "strategy", "symbol" }
        );

        // SignalSlayer decisions: atr_too_low, spread_too_wide, ticks_too_low, cap_reached, micro_filter_rejected, accepted
        _signalSlayerRejectedTotal = Metrics.CreateCounter(
            "strategy_signal_slayer_decision_total",
            "Number of signals accepted/rejected by SignalSlayer with reason code",
            new[] { "strategy", "symbol", "reason_code" }
        );

        // Pullback state machine statistics
        _pullbackDetectedTotal = Metrics.CreateCounter(
            "strategy_pullback_detected_total",
            "Number of pullbacks detected (PB started)",
            new[] { "strategy", "symbol" }
        );

        _pullbackAbortedTotal = Metrics.CreateCounter(
            "strategy_pullback_aborted_total",
            "Number of pullbacks aborted with reason",
            new[] { "strategy", "symbol", "reason" } // reason: gap_tick, thin_liquidity, trend_broken, too_long, signal_slayer_rejected
        );

        _pullbackValidBreakoutTotal = Metrics.CreateCounter(
            "strategy_pullback_valid_breakout_total",
            "Number of pullbacks that reached valid breakout (signal emitted)",
            new[] { "strategy", "symbol" }
        );

        // Time-of-day profiling: per-phase counters
        _signalsGeneratedByPhaseTotal = Metrics.CreateCounter(
            "strategy_signals_generated_by_phase_total",
            "Number of signals generated by trading phase",
            new[] { "strategy", "symbol", "phase" } // phase: preRTH, open_1h, midday, power_hour, close, afterhours, off_hours
        );

        _signalsAcceptedByPhaseTotal = Metrics.CreateCounter(
            "strategy_signals_accepted_by_phase_total",
            "Number of signals accepted by trading phase",
            new[] { "strategy", "symbol", "phase" }
        );

        _signalsBlockedByPhaseTotal = Metrics.CreateCounter(
            "strategy_signals_blocked_by_phase_total",
            "Number of signals blocked by trading phase and reason",
            new[] { "strategy", "symbol", "phase", "reason" }
        );

        _signalSlayerRejectedByPhaseTotal = Metrics.CreateCounter(
            "strategy_signal_slayer_rejected_by_phase_total",
            "Number of signals rejected by SignalSlayer by trading phase and reason code",
            new[] { "strategy", "symbol", "phase", "reason_code" }
        );

        // Hold-time model: time-exit metrics
        _timeExitOccurredTotal = Metrics.CreateCounter(
            "strategy_time_exit_occurred_total",
            "Number of time-based exits by mode, regime, and symbol baseline",
            new[] { "mode", "symbol", "regime", "baseline" } // mode: Swing/Intraday, regime: LOW/NORMAL/HIGH, baseline: slow/normal/fast
        );

        _timeExitPnlDistribution = Metrics.CreateHistogram(
            "strategy_time_exit_pnl_percent",
            "P&L percentage distribution after time-based exits",
            new[] { "mode", "regime", "baseline" }
        );

        // Trailing stop metrics
        _trailingArmedTotal = Metrics.CreateCounter(
            "strategy_trailing_armed_total",
            "Number of times trailing stop was armed (activated)",
            new[] { "symbol", "method" } // method: ATR or PCT
        );

        _trailingUpdateTotal = Metrics.CreateCounter(
            "strategy_trailing_update_total",
            "Number of times trailing stop was updated (moved up)",
            new[] { "symbol", "method" }
        );

        _trailingFireTotal = Metrics.CreateCounter(
            "strategy_trailing_fire_total",
            "Number of times trailing stop was fired (exit executed)",
            new[] { "symbol", "method" }
        );

        _trailingPnlDistribution = Metrics.CreateHistogram(
            "strategy_trailing_pnl_percent",
            "P&L percentage distribution after trailing stop exits",
            new[] { "symbol", "method" }
        );

        // Multi-day swing: gap protection metrics
        _gapExitExecutedTotal = Metrics.CreateCounter(
            "strategy_gap_exit_executed_total",
            "Number of times gap exit was executed (overnight gap loss exceeded threshold)",
            new[] { "symbol" }
        );

        _gapDetectedOnOpenTotal = Metrics.CreateCounter(
            "strategy_gap_detected_on_open_total",
            "Number of times gap was detected on market open",
            new[] { "symbol" }
        );

        _gapExitPnlDistribution = Metrics.CreateHistogram(
            "strategy_gap_exit_pnl_percent",
            "P&L percentage distribution after gap exit",
            new[] { "symbol" }
        );

        _atrFraction = Metrics.CreateGauge(
            "strategy_atr_fraction",
            "ATR as fraction of price (per symbol, last observed)",
            new[] { "strategy", "symbol" }
        );

        _pullbackDurationSeconds = Metrics.CreateGauge(
            "strategy_pullback_duration_seconds",
            "Duration of current/last pullback in seconds",
            new[] { "strategy", "symbol" }
        );
    }

    public static StrategyMetrics Instance
    {
        get
        {
            if (_instance == null)
            {
                lock (Lock)
                {
                    _instance ??= new StrategyMetrics();
                }
            }
            return _instance;
        }
    }

    // --- API ---

    public void SetupFound(string strategy, string symbol)
    {
        _setupsFoundTotal
            .Labels(strategy, symbol)
            .Inc();
    }

    public void SignalEmitted(string strategy, string symbol, string side)
    {
        _signalsEmittedTotal
            .Labels(strategy, symbol, side)
            .Inc();
    }

    public void SignalBlocked(string strategy, string symbol, string reason)
    {
        _signalsBlockedTotal
            .Labels(strategy, symbol, reason)
            .Inc();
    }

    public void SignalThrottled(string strategy, string symbol)
    {
        _signalsThrottledTotal
            .Labels(strategy, symbol)
            .Inc();
    }

    public void ObserveAtrFraction(string strategy, string symbol, double atrFraction)
    {
        _atrFraction
            .Labels(strategy, symbol)
            .Set(atrFraction);
    }

    public void ObservePullbackDuration(string strategy, string symbol, double seconds)
    {
        _pullbackDurationSeconds
            .Labels(strategy, symbol)
            .Set(seconds);
    }

    /// <summary>
    /// Records SignalSlayer decision (accepted or rejected) with stable reason code.
    /// Reason codes: atr_too_low, atr_too_high, spread_too_wide, ticks_too_low, cap_reached, micro_filter_rejected, accepted
    /// </summary>
    public void SignalSlayerDecision(string strategy, string symbol, string reasonCode)
    {
        _signalSlayerRejectedTotal
            .Labels(strategy, symbol, reasonCode)
            .Inc();
    }

    /// <summary>
    /// Records pullback detection (PB started).
    /// </summary>
    public void PullbackDetected(string strategy, string symbol)
    {
        _pullbackDetectedTotal
            .Labels(strategy, symbol)
            .Inc();
    }

    /// <summary>
    /// Records pullback abortion with reason.
    /// Reasons: gap_tick, thin_liquidity, trend_broken, too_long, signal_slayer_rejected
    /// </summary>
    public void PullbackAborted(string strategy, string symbol, string reason)
    {
        _pullbackAbortedTotal
            .Labels(strategy, symbol, reason)
            .Inc();
    }

    /// <summary>
    /// Records valid breakout (signal emitted after successful PB).
    /// </summary>
    public void PullbackValidBreakout(string strategy, string symbol)
    {
        _pullbackValidBreakoutTotal
            .Labels(strategy, symbol)
            .Inc();
    }

    // --- Time-of-day profiling: per-phase metrics ---

    /// <summary>
    /// Records signal generated (by trading phase).
    /// </summary>
    public void SignalGeneratedByPhase(string strategy, string symbol, DateTime utcNow)
    {
        var phase = TradingPhase.ToString(TradingPhase.GetPhase(utcNow));
        _signalsGeneratedByPhaseTotal
            .Labels(strategy, symbol, phase)
            .Inc();
    }

    /// <summary>
    /// Records signal accepted (by trading phase).
    /// </summary>
    public void SignalAcceptedByPhase(string strategy, string symbol, DateTime utcNow)
    {
        var phase = TradingPhase.ToString(TradingPhase.GetPhase(utcNow));
        _signalsAcceptedByPhaseTotal
            .Labels(strategy, symbol, phase)
            .Inc();
    }

    /// <summary>
    /// Records signal blocked (by trading phase and reason).
    /// </summary>
    public void SignalBlockedByPhase(string strategy, string symbol, string reason, DateTime utcNow)
    {
        var phase = TradingPhase.ToString(TradingPhase.GetPhase(utcNow));
        _signalsBlockedByPhaseTotal
            .Labels(strategy, symbol, phase, reason)
            .Inc();
    }

    /// <summary>
    /// Records SignalSlayer rejection (by trading phase and reason code).
    /// </summary>
    public void SignalSlayerRejectedByPhase(string strategy, string symbol, string reasonCode, DateTime utcNow)
    {
        var phase = TradingPhase.ToString(TradingPhase.GetPhase(utcNow));
        _signalSlayerRejectedByPhaseTotal
            .Labels(strategy, symbol, phase, reasonCode)
            .Inc();
    }

    // --- Hold-time model: time-exit outcome logging ---

    /// <summary>
    /// Records time-based exit occurrence with P&L distribution.
    /// </summary>
    /// <param name="mode">Swing or Intraday</param>
    /// <param name="symbol">Symbol</param>
    /// <param name="regime">LOW, NORMAL, or HIGH</param>
    /// <param name="baseline">slow, normal, or fast</param>
    /// <param name="pnlPercent">P&L as percentage (e.g., 2.5 for +2.5%)</param>
    /// <param name="holdingTime">Holding time in days (for Swing) or hours (for Intraday)</param>
    public void TimeExitOccurred(string mode, string symbol, string regime, string baseline, double pnlPercent, double holdingTime)
    {
        _timeExitOccurredTotal
            .Labels(mode, symbol, regime, baseline)
            .Inc();
        
        _timeExitPnlDistribution
            .Labels(mode, regime, baseline)
            .Observe(pnlPercent);
    }

    // --- Trailing stop metrics ---

    /// <summary>
    /// Records trailing stop activation (armed).
    /// </summary>
    public void TrailingArmed(string symbol, string method, double atrUsed)
    {
        _trailingArmedTotal
            .Labels(symbol, method)
            .Inc();
    }

    /// <summary>
    /// Records trailing stop update (moved up).
    /// </summary>
    public void TrailingUpdate(string symbol, string method, double atrUsed, double trailStop)
    {
        _trailingUpdateTotal
            .Labels(symbol, method)
            .Inc();
    }

    /// <summary>
    /// Records trailing stop fire (exit executed).
    /// </summary>
    public void TrailingFire(string symbol, string method, double atrUsed, double exitPrice, double entryPrice)
    {
        _trailingFireTotal
            .Labels(symbol, method)
            .Inc();
        
        // Calculate P&L percentage
        var pnlPercent = entryPrice > 0 ? ((exitPrice - entryPrice) / entryPrice) * 100.0 : 0.0;
        
        _trailingPnlDistribution
            .Labels(symbol, method)
            .Observe(pnlPercent);
    }

    // --- Multi-day swing: gap protection metrics ---

    /// <summary>
    /// Records gap exit execution (overnight gap loss exceeded threshold).
    /// </summary>
    public void GapExitExecuted(string symbol, double gapLossPercent, double ageDays, double pnlPercent)
    {
        _gapExitExecutedTotal
            .Labels(symbol)
            .Inc();
        
        _gapExitPnlDistribution
            .Labels(symbol)
            .Observe(pnlPercent);
    }

    /// <summary>
    /// Records gap detection on market open.
    /// </summary>
    public void GapDetectedOnOpen(string symbol, double gapLossPercent, double pnlPercent)
    {
        _gapDetectedOnOpenTotal
            .Labels(symbol)
            .Inc();
        
        _gapExitPnlDistribution
            .Labels(symbol)
            .Observe(pnlPercent);
    }
}